# Generated by Django 4.2.1 on 2023-08-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['created_at'], 'verbose_name': 'Requirement', 'verbose_name_plural': 'Requirements'},
        ),
    ]
