# Generated by Django 4.2.1 on 2023-06-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_requirement_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='is_active',
        ),
    ]
