# This file is ignored in production, but
# it is automatically picked up in development with:
#
#  $ docker-compose up

version: '3.8'

services:
  web:
    ports:
      - '8000:8000'
    volumes:
      - .:/app
