# Generated by Django 4.2.1 on 2023-06-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_count", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                "verbose_name": "ProductWeight",
                "verbose_name_plural": "ProductWeights",
            },
        ),
    ]
