# Generated by Django 4.2.1 on 2023-06-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
