# Generated by Django 4.2.1 on 2023-06-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Şikayət'), (1, 'Təklif'), (2, 'Vakansiya')], default=1),
        ),
    ]
