version: "3.8"

services:
  web:
    <<: &web
      image: sufle:prod
      build:
        target: production
        args:
          - DJANGO_ENV=production
      command: bash ./docker/django/gunicorn/start.sh
      volumes:
        - ./staticfiles:/var/www/static:rw
        - ./media:/var/www/media:rw
      environment:
        - DJANGO_ENV=production
        - STAGING=0
      env_file:
        - ./config/.env
