version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/cert:/etc/nginx/conf.d:ro
      - ./certbot/www/:/var/www/certbot/:ro
    networks:
      - certnet

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${TLS_EMAIL} -d ${DOMAIN_NAME} --agree-tos --non-interactive
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - certnet

networks:
  certnet:
