version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 81:80
    volumes:
      - static:/var/www/static:ro
      - media:/var/www/media:ro
      - ./docker/nginx/stage:/etc/nginx/conf.d:ro
    networks:
      - webnet

  web:
    <<: &web
      image: project:stage
      build:
        target: staging
        args:
          - DJANGO_ENV=production
          - STAGING=1
      command: bash ./docker/django/gunicorn/start.sh
      volumes:
        - static:/var/www/static:rw
        - media:/var/www/media:rw
        - .:/app:rw
      environment:
        - DJANGO_ENV=production
        - STAGING=1
      networks:
        - webnet

volumes:
  static:
  media:

networks:
  webnet:
