# Generated by Django 4.2.1 on 2023-07-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
