# Generated by Django 4.2.1 on 2023-07-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
