# Generated by Django 4.2.1 on 2023-06-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='logo',
            new_name='logo_grey',
        ),
        migrations.AddField(
            model_name='category',
            name='logo_red',
            field=models.FileField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AddField(
            model_name='category',
            name='logo_white',
            field=models.FileField(blank=True, null=True, upload_to='category/'),
        ),
    ]
