# Generated by Django 4.2.1 on 2023-07-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_logo_category_logo_grey_category_logo_red_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
